apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-huggingface
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gpt-hf-pod
  template:
    metadata:
      labels:
        app: gpt-hf-pod
    spec:
      containers:
      - name: gptcontainer
        image: darryl1975/fastapi-app:v1amd64
        command: ["uvicorn"]
        args: ["day02:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
        ports:
        - containerPort: 8000
